# Generated by Django 4.2 on 2024-02-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video')], max_length=20, verbose_name='media_type'),
        ),
    ]
