# Generated by Django 4.2 on 2024-02-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_media_media_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='BlogCategory',
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='BlogComment',
        ),
        migrations.RenameModel(
            old_name='Media',
            new_name='BlogMedia',
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['id'], 'verbose_name': 'BlogCategory', 'verbose_name_plural': 'BlogCategories'},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['id'], 'verbose_name': 'BlogComment', 'verbose_name_plural': 'BlogComments'},
        ),
    ]
