# Generated by Django 4.2 on 2024-02-19 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_remove_blogcomment_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='blogmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video'), ('audio', 'audio')], max_length=20, verbose_name='media_type'),
        ),
    ]
