# Generated by Django 4.2 on 2024-02-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogcomment_author_alter_blogmedia_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog/', verbose_name='thumbnail'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog/', verbose_name='thumbnail'),
        ),
    ]
