# Generated by Django 4.2 on 2024-02-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_price_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/', verbose_name='thumbnail'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/', verbose_name='thumbnail'),
        ),
    ]
